### ISSUE TITLE
Refatorar telinha de detalhe de produto

### ISSUE THREAD

**Issue by GedioneSouza** [tads-pi/wine-emporium#62]
o esquema de calcular frete não tem mascara para CEP
cacular frete deveria ficar em baixo do nome do produto

![image](https://github.com/tads-pi/wine-emporium/assets/86319074/7b1ef810-b43e-428c-98e8-86100ab026a7)

**Comment by kcalixto** [comment]
Fechado pq esse campo de CEP não deveria ficar nessa tela.
