### ISSUE TITLE
Visualizar detalhe do pedido (semelhante a história do sprint 5 "visualizar o resumo do meu pedido")

### ISSUE THREAD

**Issue by GedioneSouza** [tads-pi/wine-emporium#68]
**Client Logado**

Possa visualizar os detalhes dos itens pedido, o endereço e forma pagamento do pedido

- Semelhante a tela de "visualizar o resumo do meu pedido" sem o botão de concluir compra e voltar.
- Os dados recuperados para esta tela devem vir do banco de dados.
Tela de resumo tem que trazer a lista de produtos, suas quantidades, valores totais por produto, valor frete, valor total do pedido, endereço de entrega e forma de pagamento

**Comment by kcalixto** [comment]
duplicado #25
