### ISSUE TITLE
(backoffice) Visualizar a lista de pedidos e status (semelhante a história do sprint 5 "Visualizar a lista de pedidos e status")

### ISSUE THREAD

**Issue by GedioneSouza** [tads-pi/wine-emporium#69]
**Usuário Estoquista**

Visualizar a lista de pedidos e status
(semelhante a história do sprint 5 "Visualizar a lista de pedidos e status")

Para que serja possível mudar o status do pedido

- Uma lista com todos os pedidos feitos, odenados por data de forma decrescente.
- Semelhante a "Visualizar a lista de pedidos e status" - Data de pedido, número do pedido, valor total e status -   e botão de editar pedido

**Comment by kcalixto** [comment]
duplicado #25
