### ISSUE TITLE
Alterar o pedido

### ISSUE THREAD

**Issue by GedioneSouza** [tads-pi/wine-emporium#70]
**Usuário Estoquista**

Possa registrar a etapa da entrega do pedido

- Alterar o status entre os valores (aguardando pagamento, pagamento rejeitado, pagamento com sucesso, aguardando retirada, em transito, entregue).
- Uma vez alterado o status o mesmo deve ser registrado no banco.

**Comment by kcalixto** [comment]
Mapeado nessas tarefas:

#91 
#92
